package system

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

const (
	clashctlProxyBlockStart = "# >>> clashctl proxy >>>"
	clashctlProxyBlockEnd   = "# <<< clashctl proxy <<<"
	maxShellProfileBytes    = 1 * 1024 * 1024
)

// ShellProxyResult describes the managed shell proxy files.
type ShellProxyResult struct {
	ProfilePath string
	ScriptPath  string
}

// PersistShellProxyEnv writes a managed shell snippet for mixed-port mode.
func PersistShellProxyEnv(port int) (*ShellProxyResult, error) {
	if port <= 0 {
		return nil, fmt.Errorf("invalid mixed-port: %d", port)
	}

	profilePath, err := detectShellProfile()
	if err != nil {
		return nil, err
	}
	scriptPath, err := proxyScriptPath()
	if err != nil {
		return nil, err
	}
	if err := EnsureDir(filepath.Dir(scriptPath)); err != nil {
		return nil, fmt.Errorf("创建 clashctl 配置目录失败: %w", err)
	}

	script := buildProxyScript(port)
	if err := writeFilePreserveMode(scriptPath, []byte(script), 0644); err != nil {
		return nil, fmt.Errorf("写入代理环境脚本失败: %w", err)
	}

	block := fmt.Sprintf("%s\n[ -f %q ] && . %q\n%s", clashctlProxyBlockStart, scriptPath, scriptPath, clashctlProxyBlockEnd)
	if err := upsertManagedBlock(profilePath, block); err != nil {
		return nil, err
	}

	return &ShellProxyResult{
		ProfilePath: profilePath,
		ScriptPath:  scriptPath,
	}, nil
}

// RemoveShellProxyEnv removes the managed shell proxy block and script.
func RemoveShellProxyEnv() (*ShellProxyResult, error) {
	profilePath, err := detectShellProfile()
	if err != nil {
		return nil, err
	}
	scriptPath, err := proxyScriptPath()
	if err != nil {
		return nil, err
	}

	if err := removeManagedBlock(profilePath); err != nil {
		return nil, err
	}
	if err := os.Remove(scriptPath); err != nil && !os.IsNotExist(err) {
		return nil, fmt.Errorf("删除代理环境脚本失败: %w", err)
	}

	return &ShellProxyResult{
		ProfilePath: profilePath,
		ScriptPath:  scriptPath,
	}, nil
}

func buildProxyScript(port int) string {
	httpProxy := fmt.Sprintf("http://127.0.0.1:%d", port)
	allProxy := fmt.Sprintf("socks5h://127.0.0.1:%d", port)
	return strings.Join([]string{
		"# Generated by clashctl. Re-run `clashctl init` to refresh.",
		fmt.Sprintf("export HTTP_PROXY=%q", httpProxy),
		fmt.Sprintf("export HTTPS_PROXY=%q", httpProxy),
		fmt.Sprintf("export ALL_PROXY=%q", allProxy),
		"export NODE_USE_ENV_PROXY=1",
		"export http_proxy=\"$HTTP_PROXY\"",
		"export https_proxy=\"$HTTPS_PROXY\"",
		"export all_proxy=\"$ALL_PROXY\"",
		"export NO_PROXY=\"127.0.0.1,localhost,::1\"",
		"export no_proxy=\"$NO_PROXY\"",
		"",
	}, "\n")
}

func detectShellProfile() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("无法获取用户主目录: %w", err)
	}
	switch filepath.Base(strings.TrimSpace(os.Getenv("SHELL"))) {
	case "zsh":
		return filepath.Join(home, ".zshrc"), nil
	case "bash":
		return filepath.Join(home, ".bashrc"), nil
	default:
		return filepath.Join(home, ".profile"), nil
	}
}

func proxyScriptPath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("无法获取用户主目录: %w", err)
	}
	return filepath.Join(home, ".config", "clashctl", "proxy_env.sh"), nil
}

func upsertManagedBlock(path, block string) error {
	content, err := readManagedShellFile(path)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("读取 shell 配置失败: %w", err)
	}
	updated := replaceManagedBlock(string(content), block)
	if err := writeFilePreserveMode(path, []byte(updated), 0644); err != nil {
		return fmt.Errorf("写入 shell 配置失败: %w", err)
	}
	return nil
}

func removeManagedBlock(path string) error {
	content, err := readManagedShellFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("读取 shell 配置失败: %w", err)
	}
	updated := replaceManagedBlock(string(content), "")
	if err := writeFilePreserveMode(path, []byte(updated), 0644); err != nil {
		return fmt.Errorf("写入 shell 配置失败: %w", err)
	}
	return nil
}

func replaceManagedBlock(content, block string) string {
	start := strings.Index(content, clashctlProxyBlockStart)
	end := strings.Index(content, clashctlProxyBlockEnd)
	if start >= 0 && end >= start {
		end += len(clashctlProxyBlockEnd)
		content = strings.TrimRight(content[:start]+content[end:], "\n")
	}
	content = strings.TrimRight(content, "\n")
	if block == "" {
		if content == "" {
			return ""
		}
		return content + "\n"
	}
	if content == "" {
		return block + "\n"
	}
	return content + "\n\n" + block + "\n"
}

func writeFilePreserveMode(path string, data []byte, defaultMode os.FileMode) error {
	mode := defaultMode
	if info, err := os.Stat(path); err == nil {
		mode = info.Mode().Perm()
	} else if !os.IsNotExist(err) {
		return err
	}
	if err := EnsureDir(filepath.Dir(path)); err != nil {
		return err
	}
	return WriteFileAtomic(path, data, mode)
}

func readManagedShellFile(path string) ([]byte, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	info, err := f.Stat()
	if err != nil {
		return nil, err
	}
	if info.Size() > maxShellProfileBytes {
		return nil, fmt.Errorf("shell 配置文件过大: %d bytes (最大允许 %d bytes)", info.Size(), maxShellProfileBytes)
	}

	data, err := io.ReadAll(io.LimitReader(f, maxShellProfileBytes+1))
	if err != nil {
		return nil, err
	}
	if len(data) > maxShellProfileBytes {
		return nil, fmt.Errorf("shell 配置文件过大: %d bytes (最大允许 %d bytes)", len(data), maxShellProfileBytes)
	}
	return data, nil
}
